### PR TITLE
Help people who want to run tests

### PR DESCRIPTION
**Pull request by colinschmidt**
Now you can use run-asm-tests etc...

### CODE REVIEW

**Comment by jwright6323** [comment]
Do you need to include those Makefrags somewhere?

**Comment by zhemao** [comment]
Yeah, you need to include it in the Makefrag in vsim/ and verisim/

**Comment by colinschmidt** [comment]
Yeah let me push my do-the-right-thing include.

**Comment by colinschmidt** [comment]
Anyone have problems with this? @zhemao @grebe @abejgonzalez ?

**Pull request merged**
